#!/bin/bash
#
# Build script to validate blackjack

# Exit build script on first failure
set -e

# Run unit tests and calculate code coverage.
coverage run \
  --source blackjack \
  -m unittest discover
